# $JDTAUS: makefile.yml 9421 2026-05-26 05:01:09Z schulte $

name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run make
      run: make
